version: "3.9"
services:
  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: denarius
      POSTGRES_USER: denarius
      POSTGRES_HOST_AUTH_METHOD: trust
    image: "postgres:13-alpine"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - "pgdata:/var/lib/postgresql/data"
volumes:
  pgdata:
