name: Denarius CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  MIX_ENV: test

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: denarius
          POSTGRES_USER: denarius
          POSTGRES_DB: denarius_test
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        otp-version: [24.0]
        elixir-version: [1.13.0]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp-version}}
          elixir-version: ${{matrix.elixir-version}}

      - name: Install dependencies
        run: mix deps.get
      - name: Create database
        run: mix ecto.create
      - name: Run migrations
        run: mix ecto.migrate
      - name: Run tests
        run: mix test
      #- name: Check Formatting
      #run: mix format --check-formatted
      - name: Run Credo
        run: mix credo
