name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: denarius
          POSTGRES_USER: denarius
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        otp-version: [24.0]
        elixir-version: [1.13.0]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp-version}}
          elixir-version: ${{matrix.elixir-version}}
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
      - run: mix deps.get
      - run: mix ecto.create
      - run: mix ecto.migrate
      - run: mix test
