name: Denarius CI

on: push

env:
  MIX_ENV: test

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: denarius
          POSTGRES_USER: denarius
          POSTGRES_DB: denarius_test
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        otp-version: [24.0]
        elixir-version: [1.13.0]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp-version}}
          elixir-version: ${{matrix.elixir-version}}

      - run: mix deps.get
      - run: mix ecto.create
      - run: mix ecto.migrate
      - run: mix test
